name: Test

permissions:
  contents: write

on: [push]

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          rustflags: "-A warnings"
          toolchain: "nightly"
      - name: test
        run: |
          cargo install wasm-pack
          npm i pnpm -g
          pnpm i
          pnpm run build
          pnpm run test
