name: Test

permissions:
  contents: write

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4


      # TODO: why this doesn't work?
      # - uses: actions-rust-lang/setup-rust-toolchain@v1
      #   with:
      #     rustflags: "-A warnings"
      #     toolchain: "nightly"
      #     target: wasm32-unknown-unknown

      - name: test
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://rsproxy.cn/rustup-init.sh | sh -s -- -y --default-toolchain nightly
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
          rustup target add wasm32-unknown-unknown

          cargo install wasm-pack
          npm i pnpm -g
          pnpm i
          pnpm run build
          pnpm run test
